# see: https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#introduction
# see: https://www.appveyor.com/docs/environment-variables/

# General build flow
#init scripts
#Update /etc/hosts file
#Clone repository
#Restore build cache
#Configure stack
#install scripts
#Start services
#Patch version in .csproj and AssemblyInfo.cs files
#“build” phase
#“test” phase
#“package” phase
#“deploy” phase
#on_success scripts
#on_failure scripts (if the build has failed)
#on_finish scripts

image: ubuntu

environment:
  CI_OPT_CI_SCRIPT: https://github.com/ci-and-cd/maven-build/raw/v0.2.1/src/main/ci-script/lib_ci.sh
  CI_OPT_INFRASTRUCTURE: opensource
  MAVEN_SKIP_RC: true

init:
#- MAVEN_SKIP_RC=true # define environment variable like this not working

cache:
- "$HOME/.cache"
- "$HOME/.gradle"
- "$HOME/.m2"
- "$HOME/.sonar/cache"

# see: https://www.appveyor.com/docs/build-environment/
#, jdk 8, jdk 9
stack: node 9, jdk 10

install:
- ls -al
- sh: sudo apt-get update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends aria2 gnupg2 graphviz openssl whois
- sh: whois $(curl ipinfo.io/ip)
- sh: unset M2_HOME
- sh: sudo mkdir -p /opt/maven
- sh: sudo aria2c --file-allocation=none -c -x 10 -s 10 -m 0 --console-log-level=notice --log-level=notice --summary-interval=0 -d /opt/maven -o apache-maven-3.5.4-bin.zip https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip && sudo unzip /opt/maven/apache-maven-3.5.4-bin.zip -d /opt/maven > /dev/null
- sh: sudo ln -sfn apache-maven-3.5.4 /opt/maven/latest
#- sh: ls -la /opt/maven
#- sh: ls -la /opt/maven/latest/
- sh: export M3_HOME=/opt/maven/latest
- sh: export PATH=$M3_HOME/bin:$PATH
- sh: sudo mkdir -p /opt/gradle
- sh: sudo aria2c --file-allocation=none -c -x 10 -s 10 -m 0 --console-log-level=notice --log-level=notice --summary-interval=0 -d /opt/gradle -o gradle-4.8.1-all.zip https://services.gradle.org/distributions/gradle-4.8.1-all.zip && sudo unzip /opt/gradle/gradle-4.8.1-all.zip -d /opt/gradle > /dev/null
- sh: sudo ln -sfn gradle-4.8.1 /opt/gradle/latest
- sh: ls -la /opt/gradle
- sh: ls -la /opt/gradle/latest/
- sh: export GRADLE_HOME=/opt/gradle/latest
- sh: export PATH=$GRADLE_HOME/bin:$PATH
- sh: echo M3_HOME=$M3_HOME, GRADLE_HOME=$GRADLE_HOME, PATH=$PATH

services:
- docker

test_script:
- sh: ./inspect.sh

# build phase should be off as,
# by default, it’s set to MSBuild mode for automatic discovery and building of .NET Core projects (see the section below).
build: off
