#!/usr/bin/env bash

echo uname -a
uname -a

echo cat /etc/*-release
cat /etc/*-release

echo JAVA_HOME=${JAVA_HOME}

echo java version
java -version

echo docker version
docker version

if type -p node > /dev/null ; then
    echo node --version
    node --version
fi

if type -p gpg > /dev/null ; then
    echo gpg --version
    gpg --version
fi

if type -p gpg2 > /dev/null ; then
    echo gpg2 --version
    gpg2 --version
fi

if type -p openssl > /dev/null ; then
    echo openssl version
    openssl version
fi

echo mvn -version
echo PATH=$PATH
echo M3_HOME=${M3_HOME}
ls -la ${M3_HOME}/
mvn -version

echo gradle -v
echo PATH=$PATH
echo "GRADLE_HOME=${GRADLE_HOME}"
ls -la ${GRADLE_HOME}/
gradle -v

echo CI_OPT_CI_SCRIPT=${CI_OPT_CI_SCRIPT}
echo CI_OPT_INFRASTRUCTURE=${CI_OPT_INFRASTRUCTURE}
echo MAVEN_SKIP_RC=${MAVEN_SKIP_RC}

if [ "${APPVEYOR}" == "True" ] || [ "${APPVEYOR}" == "true" ]; then
    # Environment variables that are set by AppVeyor for every build:
    echo APPVEYOR ${APPVEYOR}
    echo CI ${CI}
    echo APPVEYOR_API_URL ${APPVEYOR_API_URL}
    echo APPVEYOR_ACCOUNT_NAME ${APPVEYOR_ACCOUNT_NAME}
    echo APPVEYOR_PROJECT_ID ${APPVEYOR_PROJECT_ID}
    echo APPVEYOR_PROJECT_NAME ${APPVEYOR_PROJECT_NAME}
    echo APPVEYOR_PROJECT_SLUG ${APPVEYOR_PROJECT_SLUG}
    echo APPVEYOR_BUILD_FOLDER ${APPVEYOR_BUILD_FOLDER}
    echo APPVEYOR_BUILD_ID ${APPVEYOR_BUILD_ID}
    echo APPVEYOR_BUILD_NUMBER ${APPVEYOR_BUILD_NUMBER}
    echo APPVEYOR_BUILD_VERSION ${APPVEYOR_BUILD_VERSION}
    echo APPVEYOR_BUILD_WORKER_IMAGE ${APPVEYOR_BUILD_WORKER_IMAGE}
    echo APPVEYOR_PULL_REQUEST_NUMBER ${APPVEYOR_PULL_REQUEST_NUMBER}
    echo APPVEYOR_PULL_REQUEST_TITLE ${APPVEYOR_PULL_REQUEST_TITLE}
    echo APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME ${APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME}
    echo APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH ${APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH}
    echo APPVEYOR_PULL_REQUEST_HEAD_COMMIT ${APPVEYOR_PULL_REQUEST_HEAD_COMMIT}
    echo APPVEYOR_JOB_ID ${APPVEYOR_JOB_ID}
    echo APPVEYOR_JOB_NAME ${APPVEYOR_JOB_NAME}
    echo APPVEYOR_JOB_NUMBER ${APPVEYOR_JOB_NUMBER}
    echo APPVEYOR_REPO_PROVIDER ${APPVEYOR_REPO_PROVIDER}
    echo APPVEYOR_REPO_SCM ${APPVEYOR_REPO_SCM}
    echo APPVEYOR_REPO_NAME ${APPVEYOR_REPO_NAME}
    echo APPVEYOR_REPO_BRANCH ${APPVEYOR_REPO_BRANCH}
    echo APPVEYOR_REPO_TAG ${APPVEYOR_REPO_TAG}
    echo APPVEYOR_REPO_TAG_NAME ${APPVEYOR_REPO_TAG_NAME}
    echo APPVEYOR_REPO_COMMIT ${APPVEYOR_REPO_COMMIT}
    echo APPVEYOR_REPO_COMMIT_AUTHOR ${APPVEYOR_REPO_COMMIT_AUTHOR}
    echo APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL ${APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL}
    echo APPVEYOR_REPO_COMMIT_TIMESTAMP ${APPVEYOR_REPO_COMMIT_TIMESTAMP}
    echo APPVEYOR_REPO_COMMIT_MESSAGE ${APPVEYOR_REPO_COMMIT_MESSAGE}
    echo APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED ${APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED}
    echo APPVEYOR_SCHEDULED_BUILD ${APPVEYOR_SCHEDULED_BUILD}
    echo APPVEYOR_FORCED_BUILD ${APPVEYOR_FORCED_BUILD}
    echo APPVEYOR_RE_BUILD ${APPVEYOR_RE_BUILD}
    echo PLATFORM ${PLATFORM}
    echo CONFIGURATION ${CONFIGURATION}
    # Tweak environment variables
    echo APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT ${APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT}
    echo APPVEYOR_FILE_DOWNLOAD_TIMEOUT ${APPVEYOR_FILE_DOWNLOAD_TIMEOUT}
    echo APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT ${APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT}
    echo APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT ${APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT}
    echo APPVEYOR_CACHE_SKIP_RESTORE ${APPVEYOR_CACHE_SKIP_RESTORE}
    echo APPVEYOR_CACHE_SKIP_SAVE ${APPVEYOR_CACHE_SKIP_SAVE}
    echo APPVEYOR_WAP_ARTIFACT_NAME ${APPVEYOR_WAP_ARTIFACT_NAME}
    echo APPVEYOR_WAP_SKIP_ACLS ${APPVEYOR_WAP_SKIP_ACLS}
    echo APPVEYOR_BUILD_WORKER_IMAGE ${APPVEYOR_BUILD_WORKER_IMAGE}
    echo APPVEYOR_SKIP_FINALIZE_ON_EXIT ${APPVEYOR_SKIP_FINALIZE_ON_EXIT}
    echo APPVEYOR_SAVE_CACHE_ON_ERROR ${APPVEYOR_SAVE_CACHE_ON_ERROR}
    echo APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE ${APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE}
fi
